//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class StructureTemplates
{

    private StructureTemplatePreview[] previewField;

    private StructureTemplateStructuresStructure[] structuresField;

    private string versionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Preview", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public StructureTemplatePreview[] Preview
    {
        get
        {
            return this.previewField;
        }
        set
        {
            this.previewField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Structure", typeof(StructureTemplateStructuresStructure), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public StructureTemplateStructuresStructure[] Structures
    {
        get
        {
            return this.structuresField;
        }
        set
        {
            this.structuresField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class StructureTemplatePreview
{

    private string versionField;

    private string idField;

    private string typeField;

    private string approvalStatusField;

    private string diagnosisField;

    private string treatmentSiteField;

    private string descriptionField;

    private string assignedUsersField;

    private string lastModifiedField;

    private string approvalHistoryField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ApprovalStatus
    {
        get
        {
            return this.approvalStatusField;
        }
        set
        {
            this.approvalStatusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Diagnosis
    {
        get
        {
            return this.diagnosisField;
        }
        set
        {
            this.diagnosisField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TreatmentSite
    {
        get
        {
            return this.treatmentSiteField;
        }
        set
        {
            this.treatmentSiteField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AssignedUsers
    {
        get
        {
            return this.assignedUsersField;
        }
        set
        {
            this.assignedUsersField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LastModified
    {
        get
        {
            return this.lastModifiedField;
        }
        set
        {
            this.lastModifiedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ApprovalHistory
    {
        get
        {
            return this.approvalHistoryField;
        }
        set
        {
            this.approvalHistoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class StructureTemplateStructuresStructure
{

    private string typeIndexField;

    private string colorAndStyleField;

    private string searchCTLowField;

    private string searchCTHighField;

    private string dVHLineStyleField;

    private string dVHLineColorField;

    private string dVHLineWidthField;

    private string eUDAlphaField;

    private string tCPAlphaField;

    private string tCPBetaField;

    private string tCPGammaField;

    private StructureTemplateStructuresStructureIdentification[] identificationField;

    private string idField;

    private string nameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TypeIndex
    {
        get
        {
            return this.typeIndexField;
        }
        set
        {
            this.typeIndexField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ColorAndStyle
    {
        get
        {
            return this.colorAndStyleField;
        }
        set
        {
            this.colorAndStyleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SearchCTLow
    {
        get
        {
            return this.searchCTLowField;
        }
        set
        {
            this.searchCTLowField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SearchCTHigh
    {
        get
        {
            return this.searchCTHighField;
        }
        set
        {
            this.searchCTHighField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DVHLineStyle
    {
        get
        {
            return this.dVHLineStyleField;
        }
        set
        {
            this.dVHLineStyleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DVHLineColor
    {
        get
        {
            return this.dVHLineColorField;
        }
        set
        {
            this.dVHLineColorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DVHLineWidth
    {
        get
        {
            return this.dVHLineWidthField;
        }
        set
        {
            this.dVHLineWidthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EUDAlpha
    {
        get
        {
            return this.eUDAlphaField;
        }
        set
        {
            this.eUDAlphaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TCPAlpha
    {
        get
        {
            return this.tCPAlphaField;
        }
        set
        {
            this.tCPAlphaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TCPBeta
    {
        get
        {
            return this.tCPBetaField;
        }
        set
        {
            this.tCPBetaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TCPGamma
    {
        get
        {
            return this.tCPGammaField;
        }
        set
        {
            this.tCPGammaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Identification", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public StructureTemplateStructuresStructureIdentification[] Identification
    {
        get
        {
            return this.identificationField;
        }
        set
        {
            this.identificationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class StructureTemplateStructuresStructureIdentification
{

    private string volumeIDField;

    private string volumeCodeField;

    private string volumeTypeField;

    private string volumeCodeTableField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VolumeID
    {
        get
        {
            return this.volumeIDField;
        }
        set
        {
            this.volumeIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VolumeCode
    {
        get
        {
            return this.volumeCodeField;
        }
        set
        {
            this.volumeCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VolumeType
    {
        get
        {
            return this.volumeTypeField;
        }
        set
        {
            this.volumeTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VolumeCodeTable
    {
        get
        {
            return this.volumeCodeTableField;
        }
        set
        {
            this.volumeCodeTableField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class NewDataSet
{

    private StructureTemplates[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StructureTemplate")]
    public StructureTemplates[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}
